apiVersion: v1
kind: Service
metadata:
  name: image-app
  namespace: image-app
spec:
  selector:
    app: image
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
