apiVersion: v1
kind: Service
metadata: 
  name: vote-service
  labels:
    name: vote-service
    app: voting-user
spec:
  type: NodePort
  ports:
    -port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    name: voting-user
    app: Voting Portal