apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-app
  namespace: image-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1  
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
        - name: image-app
          image: bobbybabu007/image-app:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "0.5"
              memory: "256Mi"
            requests:
              cpu: "0.2"
              memory: "128Mi"
